set(CPM_VERSION_FETCH "v0.38.7")

if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/CPM")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/CPM")
endif()
if (NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/CPM/cpmver.txt")
    file(TOUCH "${CMAKE_CURRENT_LIST_DIR}/CPM/cpmver.txt")
    file(WRITE "${CMAKE_CURRENT_LIST_DIR}/CPM/cpmver.txt" " ")
endif()

file(READ "${CMAKE_CURRENT_LIST_DIR}/CPM/cpmver.txt" CPM_CURRENT_VERSION_FETCH)

if (NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/CPM/CPM.cmake" OR (NOT (${CPM_CURRENT_VERSION_FETCH} STREQUAL ${CPM_VERSION_FETCH})))
    file(DOWNLOAD https://github.com/cpm-cmake/CPM.cmake/releases/download/${CPM_VERSION_FETCH}/CPM.cmake "${CMAKE_CURRENT_LIST_DIR}/CPM/CPM.cmake" TLS_VERIFY ON SHOW_PROGRESS)
    file(WRITE "${CMAKE_CURRENT_LIST_DIR}/CPM/cpmver.txt" ${CPM_VERSION_FETCH})
endif()
